services:
  # Define el Servicio Web (tu aplicación Laravel)
  - type: web
    name: relaciones-familia
    env: php
    plan: free
    branch: master
    buildCommand: "./build.sh"
    startCommand: "vendor/bin/heroku-php-apache2 public/"
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: relaciones-familia
          property: url
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: db-relaciones-familia
          property: connectionString

  # Define la Base de Datos
  - type: pserv
    name: db-relaciones-familia
    env: postgres
    plan: free