# Define los servicios de base de datos primero
databases:
  - name: db-relaciones-familia
    plan: free

# Define los servicios de aplicación después
services:
  - type: web
    name: web-relaciones-familia
    plan: free
    branch: master
    # No se especifica 'runtime' o 'env' para PHP, Render lo auto-detecta con composer.json
    buildCommand: "./build.sh"
    startCommand: "vendor/bin/heroku-php-apache2 public/"
    envVars:
      - key: APP_KEY
        generateValue: true # Render generará una clave segura
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: db-relaciones-familia # Se conecta a la base de datos definida arriba
          property: connectionString