services:
  - type: web
    name: web-relaciones-familia
    env: php
    plan: free
    branch: master
    buildCommand: "composer install --no-dev && npm install && npm run build && php artisan key:generate --force && php artisan migrate --force"
    startCommand: "vendor/bin/heroku-php-apache2 public/"

databases:
  - name: db-relaciones-familia
    plan: free